sudo: false
language: node_js
node_js:
  - "node"
  - "12"
  - "10"
before_install:
  - export TZ=Asia/Jakarta
  - npm install -g npm@latest
install:
  - npm install --dev
script:
  - npm test
after_success: npm run coverage